spring.application.name=SmartMeterIssuerSSI

server.port=${SERVER_PORT:15000}

spring.jpa.defer-datasource-initialization=true

# ACA-Py
aries.agent.url=${ARIES_AGENT_URL:http://localhost:30001}
aries.agent.api-key=${ARIES_AGENT_API-KEY:super-secret-key}
