springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

logging:
  level:
    root: INFO
    br.ufma.lsdi.SmartMeterVerifierSSI: DEBUG
    org.springframework.web: INFO

  pattern:
    file: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
