plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.2'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'br.ufma.lsdi'
version = '0.0.1-SNAPSHOT'
description = 'Self-Sovereign Identity (SSI) Verifier for verifier credentials for smart electricity meters, based on the Hyperledger Aries Cloud Agent Python (ACA-Py)'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'

	implementation 'org.springframework.boot:spring-boot-starter-thymeleaf'
	implementation 'org.thymeleaf.extras:thymeleaf-extras-springsecurity6'

	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server'
	testImplementation 'org.springframework.boot:spring-boot-starter-security-oauth2-authorization-server-test'

	implementation("network.idu.acapy:aries-client-python:0.10.0")

//	Docs
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:3.0.1")

	//JWT
	implementation("com.nimbusds:nimbus-jose-jwt:10.7")
	implementation("io.jsonwebtoken:jjwt-api:0.13.0")
	implementation("io.jsonwebtoken:jjwt-gson:0.13.0")
	runtimeOnly("io.jsonwebtoken:jjwt-impl:0.13.0")

	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	testImplementation 'org.springframework.boot:spring-boot-starter-security-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-thymeleaf-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}
