spring.application.name=SmartMeterVerifierSSI

# Server
server.port=${SERVER_PORT:15010}

# Services url
secure.data.collector.url=${SECURE_DATA_COLLECTOR_URL:http://localhost:8090/collector}
secure.resource.catalog.url=${SECURE_RESOURCE_CATALOG_URL:http://localhost:8092/catalog}

aries.agent.url=${ARIES_AGENT_URL:http://localhost:30011}
aries.agent.api-key=${ARIES_AGENT_API-KEY:reojg4g4g}

# SSI
#issuer.did=${ISSUER_DID:CGv9d8HE2Fkek2f1py2j7g}

# Security
jwt.secret=${JWT_SECRET:%D*G-KaPdSgVkYp3s6v9y$B?E(H+MbQeThWmZq4t7w!z%C*F)J@NcRfUjXn2r5u8}

# identifier register in blockchain with entity-manager
server.identifier=${SERVER_IDENTIFIER:smart-meter-many}
private.key.path=${PRIVATE_KEY_PATH:/home/edson/lsdi/fa/aca-py-controllers/ec-private-pkcs8.pem}

## Deve ser o mesmo que o emitido pelo issuer
#microservice.name=${MICROSERVICE_NAME:ManySmartMeterMicroservice}

## Refresh token in minutes
auth.refresh.long=720
auth.refresh.short=5

#profile
spring.profiles.active=dev